version: "3.9"
services:
  nginx_base:
    image: igorbarinov/openresty-nginx-module-vts
    volumes:
      - "./generic_conf/:/usr/local/openresty/nginx/conf/generic_conf/"
      - "./src/:/lua/src/"
  loadbalancer:
    extends:
      service: nginx_base
    volumes:
      - "./nginx_loadbalancer.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "18080:8080"
    depends_on:
      - edge
      - edge1
      - edge2

  backend:
    extends:
      service: nginx_base
    volumes:
      - "./nginx_backend.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "8080:8080"

  backend1:
    extends:
      service: nginx_base
    volumes:
      - "./nginx_backend.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "8180:8080"

  edge:
    extends:
      service: nginx_base
    volumes:
      - "./nginx_edge.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    depends_on:
      - backend
      - backend1
    ports:
      - "8081:8080"

  edge1:
    extends:
      service: nginx_base
    volumes:
      - "./nginx_edge.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    depends_on:
      - backend
      - backend1
    ports:
      - "8082:8080"

  edge2:
    extends:
      service: nginx_base
    volumes:
      - "./nginx_edge.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    depends_on:
      - backend
      - backend1
    ports:
      - "8083:8080"

  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: prometheus
    volumes:
      - ./config:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=24h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    labels:
      org.label-schema.group: "monitoring"
    depends_on:
      - edge
      - edge1
      - edge2
      - backend
      - backend1
      - loadbalancer

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "9091:3000"
